dist: trusty
sudo: required
addons:
  mariadb: '10.2'
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
notifications:
  email: false

#
# Describe the overall env.
#
language: php

php:
  - '7.1'

#
# Cache the composer and node_modules directory to speed up the the installation of dependencies.
#
cache:
  yarn: true
  directories:
    - ../Neos/Packages/Application/Neos.Neos.Ui/node_modules
    - ../Neos/Packages/Framework
    - ../Neos/Packages/Libraries
    - ../Neos/Packages/Sites
    - $HOME/.composer/cache

#
# Parallel environments, the value represents the name of the shell script which needs to be placed in `Build/TravisCi/Scripts/[name].sh`.
#
env:
  - TEST_SUITE=CodeStyle
  - TEST_SUITE=UnitTests
  - TEST_SUITE=IntegrationTests

#
# Set context to Production
#
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - export FLOW_CONTEXT=Production

#
# Install and setup the neos instance.
#
install:
  # Execute the optional install shell script for the environment.
  - if [ -f "Build/TravisCi/InstallScripts/$TEST_SUITE.sh" ]; then source Build/TravisCi/InstallScripts/$TEST_SUITE.sh; fi

  # Since all environments depend on the node dependencies, install and
  # afterwards prune them to remove extranous packages from previous/cached runs.
  - make install

#
# Execute the test environment specific shell script.
#
script:
  - if [ -f "Build/TravisCi/Scripts/$TEST_SUITE.sh" ]; then source Build/TravisCi/Scripts/$TEST_SUITE.sh; fi

#
# Execute the test environment specific after_script shell script.
#
after_script:
  - if [ -f "Build/TravisCi/AfterScripts/$TEST_SUITE.sh" ]; then source Build/TravisCi/AfterScripts/$TEST_SUITE.sh; fi
