sudo: false
notifications:
  email: false

#
# Describe the overall env.
#
language: php

php:
  - '7.1'

services:
  - mysql

#
# Cache the composer and node_modules directory to speed up the the installation of dependencies.
#
cache:
  yarn: true
  directories:
    - ../Neos/Packages/Application/Neos.Neos.Ui/node_modules
    - ../Neos/Packages/Framework
    - ../Neos/Packages/Libraries
    - ../Neos/Packages/Sites
    - $HOME/.composer/cache
    - $HOME/.nvm/versions/

#
# Parallel environments, the value represents the name of the shell script which needs to be placed in `Build/TravisCi/Scripts/[name].sh`.
#
env:
  - TEST_SUITE=CodeStyle
  - TEST_SUITE=UnitTests
  - TEST_SUITE=IntegrationTests

#
# Install nvm, the node depdencies and setup the some env variables.
#
before_install:
  # Install `nvm` since we are running in a php infrastructure based VM on TravisCI.
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - nvm install
  - nvm use
  - export FLOW_CONTEXT=Production

#
# Install and setup the neos instance.
#
install:
  # Execute the optional install shell script for the environment.
  - if [ -f "Build/TravisCi/InstallScripts/$TEST_SUITE.sh" ]; then source Build/TravisCi/InstallScripts/$TEST_SUITE.sh; fi

  # Since all environments depend on the node dependencies, install and
  # afterwards prune them to remove extranous packages from previous/cached runs.
  - yarn install

#
# Execute the test environment specific shell script.
#
script:
  - if [ -f "Build/TravisCi/Scripts/$TEST_SUITE.sh" ]; then source Build/TravisCi/Scripts/$TEST_SUITE.sh; fi

#
# Execute the test environment specific after_script shell script.
#
after_script:
  - if [ -f "Build/TravisCi/AfterScripts/$TEST_SUITE.sh" ]; then source Build/TravisCi/AfterScripts/$TEST_SUITE.sh; fi
